### ISSUE TITLE
Universal search button

### ISSUE THREAD

**Issue by naveenroyv** [mvbasov/OMN#1] opened 2023-02-06 07:16 UTC
Hi there,
Love how handy this app is. Just wanted to check - is there a way to search notes from anywhere via a search button?

**Comment by mvbasov** [comment] 2023-02-19 16:52
Thank you for attention to my project.
It is good idea to make functionality for search in all pages. But I don't know way to do it without complete application rewrite. The application, by design, has access to one page at time.
It is possible to do it by companion (plugin) application. But it will be in a far future time...

**Closed as completed by mvbasov** 2023-02-19 16:52 UTC
